development:
  adapter: postgresql
  encoding: unicode
  database: "box_development"
  pool: 5
  host: "localhost"
  password: "jack123" 

test:
  adapter: postgresql
  encoding: unicode
  database: "box_test"
  pool: 5
  host: "localhost"


production:
  adapter: postgresql
  encoding: unicode
  database: "box_production"
  pool: 5
  host: "localhost"
